# coding: utf-8

"""
    SMS Fusion API

    This is the SMS Fusion API

    OpenAPI spec version: 1.0.0
    Contact: support@smsfusion.com.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.hlr_callback import HLRCallback


class TestHLRCallback(unittest.TestCase):
    """ HLRCallback unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHLRCallback(self):
        """
        Test HLRCallback
        """
        model = swagger_client.models.hlr_callback.HLRCallback()


if __name__ == '__main__':
    unittest.main()
