# coding: utf-8

"""
    SMS Fusion API

    This is the SMS Fusion API

    OpenAPI spec version: 1.0.0
    Contact: support@smsfusion.com.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.hlr_api import HLRApi


class TestHLRApi(unittest.TestCase):
    """ HLRApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.hlr_api.HLRApi()

    def tearDown(self):
        pass

    def test_get_hlr(self):
        """
        Test case for get_hlr

        HLR number lookup
        """
        pass

    def test_get_hlr_callback(self):
        """
        Test case for get_hlr_callback

        HLR number lookup with results going to a callback URL
        """
        pass


if __name__ == '__main__':
    unittest.main()
