# coding: utf-8

"""
    SMS Fusion API

    This is the SMS Fusion API

    OpenAPI spec version: 1.0.0
    Contact: support@smsfusion.com.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.out_of_credit import OutOfCredit


class TestOutOfCredit(unittest.TestCase):
    """ OutOfCredit unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutOfCredit(self):
        """
        Test OutOfCredit
        """
        model = swagger_client.models.out_of_credit.OutOfCredit()


if __name__ == '__main__':
    unittest.main()
